language: node_js
node_js:
  - "0.10"
  - "0.12"
install:
# Install expect.
  - sudo apt-get install expect
# Old phantomjs has no "unsafe access" warning bug.
# Disregard that; only newer phantomjs works with node v0.12.
  #- npm install 'phantomjs@<1.9.8'
  - npm install
  - bin/install-nodegame-for-window.sh
before_script:
# Link testing directory into game.
  - cd nodegame/games/testergame/public/
  - ln -s ../../../../test test
  - ln -s ../../../../node_modules node_modules
  - cd ../../../..
script:
  - expect test/runtest.exp
