language: node_js
node_js: 0.10
install:
  - npm install
  - bin/install-nodegame-for-window.sh
before_script:
  - cd nodegame
  - node launcher.js &
  - sleep 5
  - cd ..
script:
  - node_modules/mocha-phantomjs/bin/mocha-phantomjs test/index.html
